[redshift]
; Set the day and night screen temperatures
temp-day=5500
; temp-night=4000
temp-night=4000

; Enable/Disable a smooth transition between day and night
fade=0

; Set the screen brightness. Default is 1.0
brightness-day=1.0
; brightness-night=0.7
brightness-night=1.0

; It is also possible to use a different gamma correction
; gamma=0.8:0.7:0.8
location-provider=manual

[manual]
; Set the location manually
lat=47.6
lon=-122.3

;[randr]
; Set the screen to adjust. Use the output of `xrandr` to find your screen name
;screen=0

;[geoclue2]
;enabled=false
