# Enable rounded corners
corner-radius = 25; # Adjust the radius as needed

# Glow halo via centered colored shadow
shadow = true;
shadow-radius = 40;
shadow-opacity = 1.0;
shadow-offset-x = -40;
shadow-offset-y = -40;
shadow-color = "#629dc8";

# Exclude shadows for polybar
shadow-exclude = [
    "class_g = 'Polybar'",
    "class_g = 'Dunst'",
    "!focused"
];

# rounded-corners-exclude = [
#     "class_g = 'Polybar'"
# ];

opacity-rule = [
  "90:class_g = 'kitty'",
  "85:class_g = 'obsidian'"
];

active-opacity = 1.0;
inactive-opacity = 1.0;
backend = "glx";

blur-method = "dual_kawase";      # or "gaussian", "box", etc.
blur-size = 8;                    # adjust for desired blur strength
blur-strength = 8;                # only for dual_kawase
blur-background = true;
