#!/bin/sh


#$HOME/.config/bspwm/display right_portrait &					# set xrandr for connected monitors (right_portrait mode)
$HOME/.config/bspwm/display &					# set xrandr for connected monitors (dual_landscape mode)
$HOME/.config/bspwm/monitors &					# update bspwm for monitor config
$HOME/.config/bspwm/touchpad &					# disable touchpad if lid closed
$HOME/.config/bspwm/settings &					# disable touchpad if lid closed
$HOME/.config/polybar/launch.sh &				# launch polybar
sxhkd &											# hotkeys
udiskie &										# automount external hard drives
nitrogen --restore &							# wallpaper
gnome-keyring-daemon &							# unlock when login (not working?)
ssh-agent &										# start ssh-agent (not working?)
#picom --config ~/.config/picom/picom.ini &		# picom config
xrdb $HOME/.Xresources &						# urxvt config
wmname LG3D &									# for java apps	


#############################
#### BSPWM configuration ####
#############################

bspc config border_radius		2
bspc config border_width        5 
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

########################
#### BSPWM coloring ####
########################

bspc config normal_border_color		      "#4c566a" 
bspc config active_border_color	          "#1e1e1e" 
bspc config focused_border_color	      "#5e81ac" 
bspc config presel_feedback_color	      "#5e81ac" 
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ... 
#find out the name of your monitor with xrandr 
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP-1-1) & 
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDM-1) &

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

