#!/bin/sh

#################
#### DISPLAY ####
#################

#m=$(xrandr --listmonitors | wc -l);

m=$(xrandr | grep " connected " | wc -l);
sleep .25;

if [ "$m" -eq "1" ]; then
	xrandr --output eDP-1-1 --mode 1920x1080 --primary --dpi 161 &
elif [ "$m" -eq "2" ]; then
	xrandr --output eDP-1-1 --mode 1920x1080 --primary --output HDMI-1 --mode 1920x1080 --scale 1x1 --right-of eDP-1-1 &
else
	xrandr --output eDP-1-1 --mode 1920x1080 --primary --dpi 161 &
fi

###################
#### AUTOSTART ####
###################

# $HOME/.config/bspwm/autostart.sh &

sxhkd &										# hotkeys
picom --config ~/.config/picom/picom.ini &	# picom config
xrdb $HOME/.Xresources &					# urxvt config
$HOME/.config/polybar/launch.sh &			# launch polybar
wmname LG3D &								# for java apps	
udiskie &									# automount external hard drives
nitrogen --restore &						# wallpaper

###################
#### MONITORS #####
###################

if [ "$m" -eq "1" ]; then
	bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 0
elif [ "$m" -eq "2" ]; then
  	bspc monitor eDP-1-1 -d 1 2 3 4 5 
  	bspc monitor HDMI-1 -d 6 7 8 9 0 
else
  	bspc monitor eDP-1-1 -d 1 2 3 4 5 
fi
 
#############################
#### BSPWM configuration ####
#############################

bspc config border_radius		2
bspc config border_width        5 
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

########################
#### BSPWM coloring ####
########################

bspc config normal_border_color		      "#4c566a" 
bspc config active_border_color	          "#1e1e1e" 
bspc config focused_border_color	      "#5e81ac" 
bspc config presel_feedback_color	      "#5e81ac" 
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ... 
#find out the name of your monitor with xrandr 
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP-1-1) & 
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDM-1) &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xset r rate 200 75 &						# set key repeat rate faster
xsetroot -cursor_name left_ptr &			# cursor config

exec ssh-agent	# start ssh-agent (not working?)
