#!/bin/sh

m=$(xrandr | grep " connected " | wc -l);
lid=$(cat /proc/acpi/button/lid/LID/state | grep "state:    " | awk '{ print $2 }')

# Allow passing of dual monitor mode to script
if [ $# -eq 0 ]; then
	mode="dual_landscape"
else
	mode=$1
fi



if [ "$m" -eq "1" ]; then

	$HOME/.screenlayout/laptop.sh &

elif [ "$m" -eq "3" ]; then

	if [ "$lid" = "closed" ]; then

		if [ "$mode" = "dual_landscape" ]; then
			$HOME/.screenlayout/lid-closed-dual-monitors.sh &
		elif [ "$mode" = "right_portrait" ]; then
			$HOME/.screenlayout/lid-closed-dual-monitors_right_portrait.sh &
		else
			$HOME/.screenlayout/lid-closed-dual-monitors_right_portrait.sh &
		fi

	else
		$HOME/.screenlayout/lid-opened-dual-monitors.sh &
	fi

elif [ "$m" -eq "2" ]; then

	if [ "$lid" = "closed" ]; then
		$HOME/.screenlayout/lid-closed-single-monitor.sh &
	else
		$HOME/.screenlayout/lid-opened-single-monitor.sh &
	fi

else
	# Unknown setup
	$HOME/.screenlayout/laptop.sh &

fi

