#!/bin/sh

m=$(xrandr | grep " connected " | wc -l);
lid=$(cat /proc/acpi/button/lid/LID/state | grep "state:    " | awk '{ print $2 }')

if [ "$m" -eq "1" ]; then
	bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 0 &
	#bspc monitor DP-1-2 --remove &
	#bspc monitor HDMI-1 --remove &
elif [ "$m" -eq "3" ]; then
	if [ "$lid" = "closed" ]; then
		bspc monitor DP-1-2 -d 1 2 3 4 5 &
		bspc monitor HDMI-1 -d 6 7 8 9 0 &
		bspc monitor eDP-1-1 --remove &A
	else
		bspc monitor DP-1-2 -d 1 2 3 4 5 & 
		bspc monitor HDMI-1 -d 6 7 8 9 &
		bspc monitor eDP-1-1 -d 0 &
	fi
else
  	bspc monitor eDP-1-1 -d 1 2 3 4 5 
fi
 
